version: "3"

services:
  bellissimo-nginx-proxy:
    container_name: bellissimo-nginx
    restart: always
    environment:
      - HTPASSWD=foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.
      - FORWARD_PORT=3000
      - FORWARD_HOST=bellissimo-web
    ports:
      - 1337:80
    image: beevelop/nginx-basic-auth

  mongo:
    restart: always
    container_name: mongo
    image: mongo
    volumes:
      - ./docker/mongodb:/data

  redis:
    restart: always
    image: redis

  bellissimo-web:
    restart: always
    image: node:20
    container_name: bellissimo-web
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm run start
    # ports:
    #   - 3000:3000
    depends_on:
      - redis
      - mongo

  bellissimo:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URI=redis://redis/
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo

  nginx:
    restart: always
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bellissimo