version: "3.8"
services:
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    volumes:
      - ./docker/mongodb:/data

  redis:
    restart: always
    image: redis

  bellissimo:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URI=redis://redis/
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo

  nginx:
    restart: always
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bellissimo