version: "3.8"
include:
  - docker-compose.yml

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./docker/wp:/var/www/html
    ports:
      - 1338:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=3xdU70UuAWtV6u74m9I44
      - WORDPRESS_DB_NAME=wordpress

  wp-db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./docker/wp-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1JoUhZ0CxhX4UKYDMLPAw
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=3xdU70UuAWtV6u74m9I44