version: "3.8"
include:
  - docker-compose.yml

services:
  influxdb:
    image: influxdb:1.7
    restart: always
    volumes:
      - ./docker/influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_DB: actualdb

  grafana:
    image: grafana/grafana
    user: root
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource, volkovlabs-grapi-datasource
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - influxdb
    volumes:
      - ./docker/grafana-storage:/var/lib/grafana